packages:
  - packages/*
allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true

loglevel: debug

minimumReleaseAgeExclude:
  - '@evnt/*'
  - react-native-worklets@0.10.2
  - '@expo/cli@57.0.11'
  - '@expo/inline-modules@0.1.4'
  - '@expo/local-build-cache-provider@57.0.5'
  - '@expo/log-box@57.0.2'
  - '@expo/prebuild-config@57.0.10'
  - babel-preset-expo@57.0.5
  - expo-asset@57.0.8
  - expo-constants@57.0.8
  - expo-modules-core@57.0.8
  - expo@57.0.9
  - '@expo/metro-runtime@57.0.8'
  - '@expo/ui@57.0.8'
  - expo-dev-client@57.0.10
  - expo-dev-launcher@57.0.10
  - expo-dev-menu@57.0.10
  - expo-router@57.0.9
  - expo-sharing@57.0.8

patchedDependencies:
  '@sqlite.org/sqlite-wasm@3.51.2-build9': patches/@sqlite.org__sqlite-wasm@3.51.2-build9.patch
